// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD01_lWMv-wCWxN_QSyFHowT9rP4HWhvFQ',
    appId: '1:254312657043:web:258b6f22a2f6c96af95d66',
    messagingSenderId: '254312657043',
    projectId: 'crud-app-5398a',
    authDomain: 'crud-app-5398a.firebaseapp.com',
    storageBucket: 'crud-app-5398a.appspot.com',
    measurementId: 'G-WLCF1S34CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClKLhyIuAorbz4GuterqGef7KyzR0NDdk',
    appId: '1:254312657043:android:51aaa9e449e84f01f95d66',
    messagingSenderId: '254312657043',
    projectId: 'crud-app-5398a',
    storageBucket: 'crud-app-5398a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGMaYrxYnZPz77sR3Iupo_TCiXpZjTtU4',
    appId: '1:254312657043:ios:f4cdf5f6868d6fbcf95d66',
    messagingSenderId: '254312657043',
    projectId: 'crud-app-5398a',
    storageBucket: 'crud-app-5398a.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );
}
